export enum ENUM_DESIGNATION {
  MYBOOK = 'mybook',
  STORY = 'story',
  INTERVIEW = 'interview',
  PROSE = 'prose',
  PHOTOGRAPH = 'photograph',
  TRAVELPROSE = 'travelprose',
  POETRY = 'poetry',
  TRANSLATION = 'translation',
  PAITING = 'paiting',
  MOVIE = 'movie',
  USER = 'user',
  ADMIN = 'admin',
  SUPER_ADMIN = 'super_admin',
}
